CREATE TABLE ReservaHabitacion(
    id number(20) GENERATED BY DEFAULT AS IDENTITY,
    fecha_entrada varchar2(20) NOT NULL,
    fecha_salida varchar2(20) NOT NULL,
    numero_personas integer NOT NULL,
    documento_cliente number(15) NOT NULL,
    id_hotel number(20) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(documento_cliente) REFERENCES Cliente(numero_documento),
    FOREIGN KEY(id_hotel) REFERENCES Hotel(id),
    CHECK(numero_personas > 0)
);