CREATE TABLE ReservaServicio(
    id number(20) GENERATED BY DEFAULT AS IDENTITY,
    fecha_entrada varchar2(50) NOT NULL,
    fecha_salida varchar2(50) NOT NULL,
    id_servicio number(20) NOT NULL,
    documento_cliente number(15) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(id_servicio) REFERENCES ServicioHotel(id),
    FOREIGN KEY(documento_cliente) REFERENCES Cliente(numero_documento)
);