CREATE TABLE Producto(
    id number(20) GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar2(50) NOT NULL,
    costo number(10) NOT NULL,
    id_servicio number(20) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(id_servicio) REFERENCES ServicioHotel(id),
    CHECK(costo > 0)
);