CREATE TABLE PlanConsumo (
    id number(20) GENERATED BY DEFAULT AS IDENTITY,
    tipo_plan varchar2(100) NOT NULL,
    descripcion varchar2(300) NOT NULL,
    id_hotel number(20)NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(id_hotel) REFERENCES Hotel(id),
    CHECK(LENGTH(TRIM(tipo_plan)) != 0),
    CHECK(LENGTH(TRIM(descripcion)) != 0)
);