CREATE TABLE InfoConsumo(
    id number(20) GENERATED BY DEFAULT AS IDENTITY,
    cantidad integer NOT NULL,
    id_producto number(20) NOT NULL,
    id_servicio number(20) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(id_producto) REFERENCES Producto(id),
    FOREIGN KEY(id_servicio) REFERENCES ServicioHotel(id),
    CHECK(cantidad > 0)
);