CREATE TABLE Consumo(
    id number(20) GENERATED BY DEFAULT AS IDENTITY,
    lugar number(20) NOT NULL,
    costo_total number(10),
    numero_habitacion varchar2(20) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(lugar) REFERENCES Lugar(id),
    FOREIGN KEY(numero_habitacion) REFERENCES Habitacion(numero),
    CHECK(costo_total >= 0)
);