CREATE TABLE ServicioHotel(
    id number(20) GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar2(100) NOT NULL,
    hora_apertura varchar2(20) NOT NULL,
    hora_cierre varchar2(20) NOT NULL,
    descripcion varchar2(300) NOT NULL,
    capacidad number(6) NOT NULL,
    costo number(10),
    lugar number(20) NOT NULL,
    disponible integer NOT NULL,
    id_hotel number(20) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(lugar) REFERENCES Lugar(id),
    FOREIGN KEY(id_hotel) REFERENCES Hotel(id),
    CHECK(capacidad > 0),
    CHECK(costo >= 0),
    CHECK(disponible >= 0),
    CHECK(disponible <= capacidad)
);